backend:
  name: git-gateway
  repo: saddathasan/pace4life-netlify
#   base_url: https://poc-20210302-045615.vercel.app/
#   auth_endpoint: api/auth
  branch: main
public_folder: "/assets/uploads" 
media_folder: "public/assets/uploads"
collections:
  - name: posts
    label: "posts"
    folder: "_cmscontent/posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
